Hw13 calendar
e-nikolaev/OTUS_Go_hw pull request #13
Opened 2023-04-18 20:23 UTC by e-nikolaev

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-04-20 15:11 UTC, dshemin requested changes

2023-04-20 15:11 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/handler.go
> +	eventsProto := api.GetResponse{}
Важно:

Общая логика для трёх методов, можно вынести.

2023-04-20 15:11 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/rest/server.go
> +	// TODO
Важно:

Что за TODO? Что-то не дореализовано?

2023-04-21 18:26 UTC, e-nikolaev commented on hw12_13_14_15_calendar/Makefile
> +generate:
Исправлено в c156dcf8912080f2169745b94da96228ee459ec6 и 04ecff57c79c1ff7d9499614c811765e67b0b640

2023-04-21 19:22 UTC, e-nikolaev commented on hw12_13_14_15_calendar/internal/server/grpc/handler.go
> +		eventsProto.Event = append(eventsProto.Event, TransformEventToProto(event))
Исправлено в 06abb9a0c02cf70c740c56ad373a60a4a7dc1000

2023-04-21 19:23 UTC, e-nikolaev commented on hw12_13_14_15_calendar/internal/server/rest/server.go
> +	// TODO
Исправлено в a1acd15d088bf37481c312467c22beecb31e33a2

2023-04-21 19:23 UTC, e-nikolaev commented on hw12_13_14_15_calendar/internal/server/rest/server.go
> +	// TODO
Остался артефакт от шаблона с ДЗ, забыл удалить

2023-04-22 07:27 UTC, dshemin approved these changes

2023-04-22 07:51 UTC, merged