HW3 is completed
e-nikolaev/OTUS_Go_hw pull request #3
Opened 2022-12-25 10:31 UTC by e-nikolaev

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-25 16:06 UTC, dshemin requested changes

2022-12-25 16:06 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +		uniqWord := uniqWordExpr.FindString(strings.ToLower(rawWord))
Важно:

Регулярка стоит очень дорого. Можно решить без неё.

2022-12-25 16:06 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +	resultSlice := make([]string, resultLen)
Важно:

Можно обойтись без создания дополнительного слайса используя возможности слайсов
```
var s = []int{1, 2, 3, 4, 5}
s[2:4]
```

2022-12-25 17:36 UTC, e-nikolaev commented on hw03_frequency_analysis/top.go
> +			if found {
Fixed in [71da8ba](https://github.com/e-nikolaev/OTUS_Go_hw/pull/3/commits/71da8baf911e41c3b67a4ac3384ff2c7c3cb26a5)

2022-12-25 17:37 UTC, e-nikolaev commented on hw03_frequency_analysis/top.go
> +	resultSlice := make([]string, resultLen)
Fixed in [d776cad](https://github.com/e-nikolaev/OTUS_Go_hw/pull/3/commits/d776cadcd6a28959e4f16474de8c3c5951c72dbd)

2022-12-25 17:38 UTC, e-nikolaev commented on hw03_frequency_analysis/top.go
> +		uniqWord := uniqWordExpr.FindString(strings.ToLower(rawWord))
Fixed in [d776cad](https://github.com/e-nikolaev/OTUS_Go_hw/pull/3/commits/d776cadcd6a28959e4f16474de8c3c5951c72dbd)

2022-12-25 17:40 UTC, e-nikolaev commented on hw03_frequency_analysis/top.go
> +	resultSlice := make([]string, resultLen)
Там слайсы с разными типами даных, в теле фуyкции используется слайс с типом `WordCountStruct`, вернуть нужно слайс из строк

2022-12-26 07:17 UTC, dshemin approved these changes

2022-12-26 07:17 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +			if found {
Важно:

Вы немного не поняли. Можно упростить намного больше. Попробуйте убрать код с 23 до 28 строки и заменить на wordsCountMap[uniqWord]++.

2022-12-26 07:17 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +	resultSlice := make([]string, resultLen)
Всё верно. Поэтому можно сразу создать массив слов вместо структур и сортировать его по мапе.

2022-12-26 08:00 UTC, merged